CREATE TABLE [dbm].[Instance] (
    [InstanceId]                 NVARCHAR (128)   NOT NULL,
    [Hostname]                   NVARCHAR (255)   NULL,
    [Port]                       NVARCHAR (5)     NULL,
    [DeviceId]                   NVARCHAR (24)    NOT NULL REFERENCES [dbm].[Device] ([DeviceId]),
    [Version]                    NVARCHAR (300)   NULL,
    [Edition]                    NVARCHAR (128)   NULL,
    [Level]                      NVARCHAR (128)   NULL,
    [ProductUpdateLevel]         NVARCHAR (128)   NULL,
    [ProductUpdateReference]     NVARCHAR (128)   NULL,
    [ResourceLastUpdateDateTime] NVARCHAR (128)   NULL,
    [ProductVersion]             NVARCHAR (128)   NULL,
    [DBEAccount]                 NVARCHAR (256)   NULL,
    [AgentAccount]               NVARCHAR (256)   NULL,
    [InstanceDefaultDataPath]    NVARCHAR (128)   NULL,
    [InstanceDefaultLogPath]     NVARCHAR (128)   NULL,
    [BackupDirectory]            NVARCHAR (256)   NULL,
    [ServerState]                VARCHAR (6)      NULL,
    [IsSingleUser]               NVARCHAR (128)   NULL,
    [Collation]                  NVARCHAR (128)   NULL,
    [MonitorDisk]                BIT              DEFAULT ('FALSE') NULL,
    [MonitorRAM]                 BIT              DEFAULT ('FALSE') NULL,
    [MonitorCPU]                 BIT              DEFAULT ('FALSE') NULL,
    [RemoteBackup]               BIT              DEFAULT ('FALSE') NULL,
    [Environment]                NVARCHAR (12)    NULL,
    [Description]                NVARCHAR (128)   NULL,
    [Owner]                      NVARCHAR (128)   NULL,
    [Listener]                   NVARCHAR (128)   NULL,
    [Login]                      NVARCHAR (128)   NULL,
    [Password]                   VARBINARY (8000) NULL,
    [Comments]                   NVARCHAR (MAX)   NULL,
    [LicenseKey]                 NVARCHAR(64)     NULL,
    [PhysicalCPUs]               INT NULL,
    [Cores]               INT NULL,
    [LogicalCPUs]               INT NULL,
    [DataImportUTC]              DATETIME         DEFAULT (getutcdate()) NULL,
    CONSTRAINT [PK.instance.InstanceId] PRIMARY KEY CLUSTERED ([InstanceId] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK.DB.DeviceId] FOREIGN KEY ([DeviceId]) REFERENCES [dbm].[Device] ([DeviceId]) ON DELETE CASCADE ON UPDATE CASCADE
);

