CREATE TABLE [dbm].[Script]
(
	[Id] INT NOT NULL IDENTITY(1,1) PRIMARY KEY CLUSTERED ([Id]),
	[ScriptName] NVARCHAR(128) NOT NULL,
	[Database] NVARCHAR(128) NULL,
	[Requirements] NVARCHAR(MAX) NULL,
	[TSql] NVARCHAR(MAX) NULL,
	[DataImportUTC] DATETIME NULL DEFAULT GETUTCDATE(),
	[Version] AS 'Version '+CONVERT(VARCHAR(4),DATEPART(YEAR,GETUTCDATE()))+'.'+CONVERT(VARCHAR(2),DATEPART(MONTH,GETUTCDATE()))+'.'+CONVERT(VARCHAR(2),DATEPART(DAY,GETUTCDATE()))	
)
