CREATE TRIGGER [dbm].[InstanceI] ON [dbm].[Instance] INSTEAD OF INSERT AS
BEGIN

	INSERT INTO [dbm].[Device] ([DeviceId],[DataImportUTC]) SELECT DeviceId,GETUTCDATE() AS [DataImportUTC] FROM Inserted WHERE DeviceId NOT IN (SELECT DeviceId FROM [dbm].[Device])	
	--UPDATE Inserted SET DeviceId=ISNULL(Inserted.DeviceId,Inserted.InstanceId) FROM Inserted WHERE DeviceId NOT IN (SELECT DeviceId FROM [dbm].[Device])
	INSERT INTO [dbm].[Instance]
	(
	    [InstanceId],
	    [Hostname],
	    [Port],
	    [DeviceId],
	    [Version],
	    [Edition],
	    [Level],
	    [ProductUpdateLevel],
	    [ProductUpdateReference],
	    [ResourceLastUpdateDateTime],
	    [ProductVersion],
	    [DBEAccount],
	    [AgentAccount],
	    [InstanceDefaultDataPath],
	    [InstanceDefaultLogPath],
	    [BackupDirectory],
	    [ServerState],
	    [IsSingleUser],
	    [Collation],
	    [MonitorDisk],
	    [MonitorRAM],
	    [MonitorCPU],
	    [RemoteBackup],
	    [Environment],
	    [Description],
	    [Owner],
	    [Listener],
	    [Login],
	    [Password],
	    [Comments],
	    [LicenseKey],
	    [DataImportUTC]
	)
	SELECT [InstanceId],
	    [Hostname],
	    [Port],
	    ISNULL([DeviceId],[InstanceId]) AS [DeviceId],
	    [Version],
	    [Edition],
	    [Level],
	    [ProductUpdateLevel],
	    [ProductUpdateReference],
	    [ResourceLastUpdateDateTime],
	    [ProductVersion],
	    [DBEAccount],
	    [AgentAccount],
	    [InstanceDefaultDataPath],
	    [InstanceDefaultLogPath],
	    [BackupDirectory],
	    [ServerState],
	    [IsSingleUser],
	    [Collation],
	    [MonitorDisk],
	    [MonitorRAM],
	    [MonitorCPU],
	    [RemoteBackup],
	    [Environment],
	    [Description],
	    [Owner],
	    [Listener],
	    [Login],
	    [Password],
	    [Comments],
	    [LicenseKey],
	    [DataImportUTC] FROM Inserted
END
