/*
CREATE VIEW [dbm].[_SQLPatch] AS
SELECT CV.SQLPatch, CV.SQLServerId,CV.CUN,CV.SQLPatchDate,'Compliant' AS CE FROM (
SELECT SP.SQLPatch, SP.SQLServerId,SP.CUN,SP.SQLPatchDate 
	,ROW_NUMBER() OVER (PARTITION BY SP.SQLServerId ORDER BY SP.SQLServerId,SP.SQLPatchDate DESC) AS [RN]
FROM [dbm].[SQLPatch] SP) CV WHERE CV.[RN]=1
UNION ALL
SELECT CV.SQLPatch, CV.SQLServerId,CV.CUN,CV.SQLPatchDate,'Upgrade' AS CE FROM (
SELECT SP.SQLPatch, SP.SQLServerId,SP.CUN,SP.SQLPatchDate 
	,ROW_NUMBER() OVER (PARTITION BY SP.SQLServerId ORDER BY SP.SQLServerId,SP.SQLPatchDate DESC) AS [RN]
FROM [dbm].[SQLPatch] SP) CV WHERE CV.[RN]=2
UNION ALL
SELECT CV.SQLPatch, CV.SQLServerId,CV.CUN,CV.SQLPatchDate,'Non compliant' AS CE FROM (
SELECT SP.SQLPatch, SP.SQLServerId,SP.CUN,SP.SQLPatchDate 
	,ROW_NUMBER() OVER (PARTITION BY SP.SQLServerId ORDER BY SP.SQLServerId,SP.SQLPatchDate DESC) AS [RN]
FROM [dbm].[SQLPatch] SP) CV WHERE CV.[RN]>2
*/